platform :ios, '9.0'
 
inhibit_all_warnings!
use_frameworks!
 
target ‘rondo’ do
  pod 'Alamofire', '~> 3.1.2'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end